### PR TITLE
Add reference paper, update mkdocs

### PR DESCRIPTION
**Pull request by swertz**
Here's what it looks like:

screenshot_20181009_223320

The link is to Inspire. Should we put the actual citation people have to use?

### CODE REVIEW

**Comment by delaere** [comment]
Looks good to me. Thanks.
People should know how to cite a paper from inspire. In this case I think that we'd better not give it explicitly, because of the utf characters (what an idea to have a "é" in your first name ;-) )

**Comment by swertz** [comment]
Good point ^^ Maybe we could make it stand out more, as a "note" in https://momemta.github.io/in-depth/calling-momemta/ ?

**Comment by delaere** [comment]
good idea

**Comment by swertz** [comment]
Done!

**Pull request merged**
