### PR TITLE
Add some text on how-to build

### PR DESCRIPTION
**Pull request by blinkseb**

### CODE REVIEW

**Comment by vidalm** [comment]
Stupid one. I would change the last sentence:

You can find more details -> Find more details ...
3 sentences all starting with You can.

**Comment by blinkseb** [comment]
Ah yes, sure :)

**Comment by blinkseb** [comment]
I've updated the text, thanks for the feedback!

**Comment by swertz** [comment]
Nice! So we don't add any details there, only redirect to the readme? I'm wondering if it's even necessary to mention the commands here if that's the case?

**Comment by blinkseb** [comment]
Yes indeed, it's maybe better to redirect to a page with more content. I'm closing this

**Pull request closed without merging**
